### ISSUE TITLE
Twig template captcha doesnt display

### ISSUE THREAD

**Issue by oMolloMo** [Bee-Lab/BeelabRecaptcha2Bundle#1]
I followed every step, but the captcha doesnt show. The Div appears in the html code but it is empty. Which javascripts files should I add to my twig view to display the captcha?

**Comment by garak** [comment]
You're right, I missed to mention that a JavaScript is needed. As documented in Recaptcha docs, you need to include ``https://www.google.com/recaptcha/api.js?hl=en`` (changing ``hl`` parameter to whatever appropriate for you).
I'll update docs asap.
