### ISSUE TITLE
PHP 5.5 requirement

### ISSUE THREAD

**Issue by guilhermednt** [Bee-Lab/BeelabRecaptcha2Bundle#12]
Where I work at we are restricted to PHP 5.4.16 (so are everyone running RHEL 7) and this bundle now requires PHP 5.5 as of commit 46129f0d5eb72582aef95c6e16d4e7a3b5ff482c.

Would it be possible to create a tag (or branch) pointing to f0f566168739a38ab3828156496830702e7807b1 so that we can still install the version we were using before? This way I won't have to create a fork just for that since [composer won't let me just point to the commit because:](https://getcomposer.org/doc/04-schema.md#package-links)

> The composer.json metadata will still be read from the branch name you specify before the hash.

**Comment by garak** [comment]
Can't you use tag `v0.2.0`?

**Comment by guilhermednt** [comment]
Unfortunately not because I need the change introduced by PR #11 since we don't have access to `file_get_contents` here.

If you think it's too much hassle I could just use a fork, but probably people using RHEL 7 won't be able to use the bundle (I'm assuming `file_get_contents` is disabled by default).

**Comment by garak** [comment]
Now there's a `legacy` branch and a `v0.3.0` tag. Use that.

**Comment by guilhermednt** [comment]
Thanks!

**Comment by garak** [comment]
You're welcome. And, if I can give you a suggestion, upgrade to php 5.6 as soon as possible. It's not so hard on RHEL, it's just a matter of adding a repository

**Comment by guilhermednt** [comment]
I would if I could. Unfortunately it's against the company policy to install anything that isn't in a stock RHEL so I end up spending lots of time adapting code to work with 5.4. :(
