### ISSUE TITLE
StyleCI short_array_syntax configuration

### ISSUE THREAD

**Issue by Th3Mouk** [Bee-Lab/BeelabRecaptcha2Bundle#16]
Hello !

It's seems the styleCI is missconfigured for PHP5.5 short array syntax.

The parameters is `short_array_syntax`, I don't know if he can't be applied.

## Examples 
https://styleci.io/analyses/8wW5OW
https://styleci.io/analyses/qoW57K

**Comment by garak** [comment]
It was configured for the old version. It's fixed now. Thanks!
