### ISSUE TITLE
Allow multiple instances of reCAPTCHA on the same page

### ISSUE THREAD

**Issue by cassianotartari** [Bee-Lab/BeelabRecaptcha2Bundle#17]
Hi!

Is there any way to achieve this? Add multiple instances of recaptacha on a single page.

Thanks!

**Comment by garak** [comment]
What is the purpose?

**Comment by cassianotartari** [comment]
I have multiple contacts form in the same page.

**Comment by cassianotartari** [comment]
Here it's a example: https://www.muva.com.br/imovel/lancamento-apartamento-2-quartos-1-suite-3-banheiros-2-garagens-centro-rio-grande-rs-193-mil-mcod-46548.html

1st form is the last "picture".
2nd is a little down on page.

And still have other type of form that you just submit your phone.

**Comment by garak** [comment]
I didn't try it, but maybe you could try to share your captcha instances across forms: define captchas in all your form classes, then render only the one in the first form. Subsequent forms should get the same captcha, with a bit of javascript

**Comment by cassianotartari** [comment]
I'll try something like you said plus this http://stackoverflow.com/a/28126317

**Comment by garak** [comment]
Can we close this?
