### ISSUE TITLE
Ability to hide valid captcha on invalid form after first submition

### ISSUE THREAD

**Issue by zhil** [Bee-Lab/BeelabRecaptcha2Bundle#20]
When form is invalid, but captch is valid - we could skip captcha on form generation.
Probably, something like session flag (based on form name+route name?)

What do you think?

**Comment by garak** [comment]
I assume that CAPTCHA is a special field, more or less like input file, so is behaving differently from "classic" fields. So, it needs to be displayed every time, no matter if you satisfied its needs before

**Comment by garak** [comment]
2.3 is unsupported by Symfony (and so is unsupported by us)
