### ISSUE TITLE
fix 2.3

### ISSUE THREAD

**Issue by tigerman** [Bee-Lab/BeelabRecaptcha2Bundle#21]
$ git branch fix-2.3 v0.2.0
$ git checkout fix-2.3
add in Resources/config/services.xml row 17 strict="false"
$ git commit -am 'fix 2.3'
$ git tag -a v0.2.1

**Comment by garak** [comment]
What? :confused:

**Comment by tigerman** [comment]
Symfony 2.3 error:
Scope Widening Injection detected: The definition "beelab_recaptcha2.verifier" references the service "request" which belongs to a narrower scope. Generally, it is safer to either move "beelab_recaptcha2.verifier" to scope "request" or alternatively rely on the provider pattern by injecting the container itself, and requesting the service "request" each time it is needed. In rare, special cases however that might not be necessary, then you can set the reference to strict=false to get rid of this error.

**Comment by garak** [comment]
2.3 is unsupported by Symfony (and so is unsupported by us)

**Comment by tigerman** [comment]
But this is not difficult. Just make v0.2.1

**Comment by garak** [comment]
Fixed

**Comment by tigerman** [comment]
Thanks!
