### ISSUE TITLE
Request Stack is of Symfony >2.4

### ISSUE THREAD

**Issue by Chrysweel** [Bee-Lab/BeelabRecaptcha2Bundle#3]
I have a project in symfony2.3 and I want use this bundle. 
But I see the following error:
> The service "beelab_recaptcha2.verifier" has a dependency on a non-existent service "request_stack".

The reason is, that request stack is of symfony2.4. You can see here.
http://symfony.com/blog/new-in-symfony-2-4-the-request-stack

So this bundle require change dependence in composer, or change this service...

:)

**Comment by garak** [comment]
I raised the requirement to Symfony 2.4 and created a ``0.1`` branch, that is compatible with Symfony 2.3 (so it uses ``request`` instead of ``request_stack``).
Please try it and let me know

**Comment by garak** [comment]
I just tried myself, branch ``0.1`` is OK.

**Comment by Chrysweel** [comment]
Hello @garak sorry for delay but I was very busy.

Branch 0.1 work correctly, thanks you, I will update to environment production !  ; )

Thanks again ! :+1:
