### ISSUE TITLE
Display error message

### ISSUE THREAD

**Issue by Joozty** [Bee-Lab/BeelabRecaptcha2Bundle#30]
Hi, is it possible show error message in form if captcha was wrong. 

I need to do it on server side. 

Here is my simple twig template:
```php
{{ form_start(form) }}

<div>
     {{ form_widget(form.email) }}
</div>

{% if "message" in form_errors(form.captcha) %}
    <span style='color: red;'>Invalid captcha.</span>
{% endif %}

{{ form_widget(form.captcha) }}

{{ form_end(form) }}
```

Form setup:
```php
...
            ->add('captcha', 'Beelab\Recaptcha2Bundle\Form\Type\RecaptchaType', array(
                'constraints' => new Recaptcha2(array(
                    'message' => 'Custom message'
                )),
                'mapped' => false,
                'required' => true,
            ))
...
```

Thanks in advance.

**Comment by garak** [comment]
What about `{{ form_errors(form) }}`?

**Comment by Joozty** [comment]
@garak Thanks for very quick reply. What do you mean?

I need only check if Captcha was invalid or not. At least make captcha required field. 

This doesn't seem to work:
`  'required' => true,`

**Comment by garak** [comment]
Well, in your first message you said you need to display an error.
Anyway, the captcha is already required, so please explain what are your expectations and where such expectations are not met

**Comment by Joozty** [comment]
@garak Yes I need to display error message if captcha wasn't entered or was wrong. Right now I can submit form without fill captcha input field even when I added `'required' => true,`. . So my idea is check captcha on server side and if wasnt entered or was wrong show error message in red color above captcha field.

**Comment by garak** [comment]
You're doing something wrong. Please re-check documentation and your code.

**Comment by Joozty** [comment]
@garak There is not much to setup. My whole setup is in the first message and I think it is correct. `{{ form_errors(form) }}` did the trick but this include all errors even when captcha was correct but email address was incorrect.

**Comment by garak** [comment]
Try to replace `{{ form_widget(form.captcha) }}` with `{{ form_row(form.captcha) }}`

**Comment by Joozty** [comment]
@garak Thank you for help. It was my misunderstanding how this bundle works. :)
