### ISSUE TITLE
reCAPTCHA dependency

### ISSUE THREAD

**Issue by rowan-m** [Bee-Lab/BeelabRecaptcha2Bundle#31]
You have `google/recaptcha` as a dependency. I've recently updated this with a `1.2` release. It *should* be backwards compatible, but obviously you'd want to test that. Happy to respond to issues over at https://github.com/google/recaptcha

**Comment by garak** [comment]
Thanks for letting us know.
Our current constraint for your library (`^1.1`) is allowing any minor version.
