### ISSUE TITLE
FOSUserBundle integration

### ISSUE THREAD

**Issue by cernohous-adam** [Bee-Lab/BeelabRecaptcha2Bundle#32]
Hi, 
thank you for this Symfony bundle. Everything works perfect except integration into FOSUserBundle.

I tried implement RecaptchaType into FOS registration form. Recaptcha showed on the frontend but when the form is submitted, recaptcha is not required and form is successfully sent. Did you try it implements into FOS sometimes?

I appreciate of your help,

Adam

**Comment by garak** [comment]
Well, I can't imagine any reason for the FOS registration form to be different from any other form.
Did you check that you're using the right validation group?

**Comment by cernohous-adam** [comment]
I check it once again and you're right. My validation group is "AcmeRegistration" instead of "Registration". My fault.

Thank you very much Garak!
