### ISSUE TITLE
Why was forced inline style "display: none" added?

### ISSUE THREAD

**Issue by alexeybelyy** [Bee-Lab/BeelabRecaptcha2Bundle#40]
Why was forced inline style added for invisible recaptcha?

https://github.com/Bee-Lab/BeelabRecaptcha2Bundle/blob/master/templates/form_fields.html.twig#L7

**Comment by garak** [comment]
Because invisible needs to be not displayed?

**Comment by alexeybelyy** [comment]
But how can I then display the submit button with callback function?

**Comment by garak** [comment]
You don't need it. You can use a normal submit button.
Recaptcha button is something related only to recaptcha, not to your form rendering
