### ISSUE TITLE
Invisible ReCaptcha script function not triggered

### ISSUE THREAD

**Issue by RubenColpaert** [Bee-Lab/BeelabRecaptcha2Bundle#41]
Hi, I am having troubles to implement the Invisible ReCaptcha type. The issue is, if I understand the documentation correctly, I end up with two submit buttons in my form. One is from the RecaptchaSubmitType and is invisible, which seems to be as expected according to this issue: https://github.com/Bee-Lab/BeelabRecaptcha2Bundle/issues/40. The other one is a submit button I added, as is required according to the answer of @garak in that same issue.

It does work if I overwrite the `beelab_recaptcha2_submit_widget` widget and remove the `style: 'display: none'` part from https://github.com/Bee-Lab/BeelabRecaptcha2Bundle/blob/master/templates/form_fields.html.twig#L7. However, I feel that this is probably not how this is intended to work.

Here is my simplified code:

In my form type:
```php
        $builder->add('captcha', RecaptchaSubmitType::class, [
            'constraints' => new Recaptcha2(['groups' => ['create']])
        ]);
```

In my form:
```
    {{ form_start(form, {'attr': {'novalidate':'novalidate'}}) }}
        {{ form_row(form.captcha) }}
        <button class="btn btn-primary" type="submit">Submit</button>
    {{ form_widget(form._token) }}
    {{ form_end(form, {'render_rest': false}) }}

<script src="https://www.google.com/recaptcha/api.js?hl={{ app.request.locale }}" async defer></script>
<script>
    function recaptchaCallback(token) {
        var elem = document.querySelector(".g-recaptcha");
        while ((elem = elem.parentElement) !== null) {
            if (elem.nodeType === Node.ELEMENT_NODE && elem.tagName === 'FORM') {
                elem.submit();
                break;
            }
        }
    }
</script>
```

PS: In the docs a closing bracket in the recaptchaCallback function script is missing.

**Comment by garak** [comment]
You don't need to explicitly render captcha in your form (nor your token).
Indeed, I'm using invisible recaptcha even without the callback, so you can try also whitout that part

**Comment by RubenColpaert** [comment]
This doesn't make sense to me. If I don't render the captcha type in my form (leaving out `{{ form_row(form.captcha) }}` in my form), how is it going to be triggered and when is a request going to be send to google?

**Comment by RubenColpaert** [comment]
In the end I used another package.

**Comment by garak** [comment]
You should avoid using `{'render_rest': false}`
