### ISSUE TITLE
Recaptcha 

### ISSUE THREAD

**Issue by NathanDierickx** [Bee-Lab/BeelabRecaptcha2Bundle#43]
Hello,
I have a problem with your recaptcha bundle.

I can't verify if the recaptcha is empty in my symfony form.
When submit my form with empty recaptcha. The processus work but, i would like verify the recaptcha status before submit my form.

Please help me :(

**Comment by NathanDierickx** [comment]
I try to use the recaptcha validtor but i have this error :
`Cannot autowire service "App\Controller\ContactController": argument "$recaptcha2Validator" of method "__construct()" references class "Beelab\Recaptcha2Bundle\Validator\Constraints\Recaptcha2Validator" but no such service exists. You should maybe alias this class to the existing "beelab_recaptcha2.validator" service.`

**Comment by garak** [comment]
You should not use the validator directly. Follow the documentation and add a constraint to your form.

**Comment by NathanDierickx** [comment]
Yes, I succeded this, but now I would like to get a error message and add this in my template

**Comment by garak** [comment]
The only error you need is the one provided by the constraint ("Invalid ReCaptcha.").

**Comment by NathanDierickx** [comment]
Yes, can get this error value in template twig ?

**Comment by garak** [comment]
> Yes, can get this error value in template twig ?

Of course, like any other form errors
