### ISSUE TITLE
seeing it in dev environment

### ISSUE THREAD

**Issue by Soolan** [Bee-Lab/BeelabRecaptcha2Bundle#5]
Hi,
I was wondering if we can not see the captcha in the dev or test environment, how can we use it?
I mean before deploying anything to production server, you have to check if it works right?

I installed and configured the bundle without any problem, but now I can not see it in my form (registration form for example).

But if I include the google s file in my template and hard code the following div into my template I can see it:
`<div class="g-recaptcha" data-sitekey="some-site-key-blah-blah"></div>`

Can you expand it a little please?

**Comment by garak** [comment]
You should see the captcha in dev environment.
Captcha should be disabled in test environment only, since it's not possible to test it.

**Comment by Soolan** [comment]
Wow thanks for the quick reply.
So after setting all the required configurations, do I need to add a div like this to the template?
        <div class="g-recaptcha" data-sitekey="{{ site_key }}"></div>


My understanding was when you add add a form field of recaptcha type, it should be added to the form automatically. Can you explaint it please?

**Comment by garak** [comment]
Everything should work just by following docs.
The div is added by form template. The template is added by the compiler pass.

**Comment by Soolan** [comment]
You are right, I had a missing 'use' statement.
Thank you for your help
