### ISSUE TITLE
Is there a way to add display vars?

### ISSUE THREAD

**Issue by sebastianlp** [Bee-Lab/BeelabRecaptcha2Bundle#6]
In first place I want to thankyou and congratulate you for this bundle, it's very easy to implement and the validation is superb.

Following the [documentation ](https://developers.google.com/recaptcha/docs/display) we can customize the display of the widget with some data-* parameters. Looking inside the code, only data-param present is the data-sitekey.
Following the configuration of the bundle, I've setup the data-theme inside my parameters.yml and inject it to the bundle, but, is this the best way if we want to add all data-* params?

Thank you in advance!

**Comment by garak** [comment]
You can override bundle's template, see docs: http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates
In your custom template, you can directly set any data-* parameter.

**Comment by sebastianlp** [comment]
Thank you @garak.

I'll close this issue so.
