### ISSUE TITLE
Deprecations in Symfony 2.8

### ISSUE THREAD

**Issue by MECU** [Bee-Lab/BeelabRecaptcha2Bundle#7]
Great work with this!

These prevent upgrading to Symfony 3.0.

I'm on v1.0.0

Both in `RecaptchaType.php`

### getName()
Deprecation notice:
> Beelab\Recaptcha2Bundle\Form\Type\RecaptchaType: The FormTypeInterface::getName() method is deprecated since version 2.8 and will be removed in 3.0. Remove it from your classes. Use getBlockPrefix() if you want to customize the template block prefix. This method will be added to the FormTypeInterface with Symfony 3.0.

This:
```php
    public function getName()
    {
        return 'beelab_recaptcha2';
    }
```

Should now be:

```php
    public function getBlockPrefix()
    {
        return 'beelab_recaptcha2';
    }
```

### form Type
> Accessing type "form" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\FormType" instead.

This:
```php
    public function getParent()
    {
        return 'form';
    }
```

Should now be:
```php
use Symfony\Component\Form\Extension\Core\Type\FormType;

    public function getParent()
    {
        return FormType::class;
    }
```
Though the `::class` requires PHP 5.5+. This should be okay since 5.4 and lower are end of life (EOL). http://php.net/supported-versions.php

I'll do a pull request, if desired.

**Comment by lechaabani** [comment]
Great work :+1: 

If the parent of my formType is an other:

```
public function getParent()
    {
        return new CorporateType();
    }
```

How i can change it in sf2.8

**Comment by garak** [comment]
You need to use the FQCN

**Comment by lechaabani** [comment]
@garak  thank you :+1:
